#
#    This file is part of the Salt Minion Inventory.
#
#    Salt Minion Inventory provides a web based interface to your
#    SaltStack minions to view their state.
#
#    Copyright (C) 2019-2023 Neil Munday (neil@mundayweb.com)
#
#    Salt Minion Inventory is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Salt Minion Inventory is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Salt Minion Inventory.  If not, see <http://www.gnu.org/licenses/>.
#

FROM rockylinux:8

ARG SALT_VERSION=3005

RUN dnf install -y dnf-plugins-core procps-ng && \
    dnf update -y && \
    dnf install -y epel-release && \
    dnf config-manager --set-enabled powertools && \
    dnf install -y iproute

# salt install
COPY --chown=root tests/salt.repo /etc/yum.repos.d/

RUN sed -i "s/SALT_VERSION/$SALT_VERSION/" /etc/yum.repos.d/salt.repo

RUN dnf install -y salt-minion

# configure salt
COPY tests/salt-minion.conf /tmp/
RUN cat /tmp/salt-minion.conf >> /etc/salt/minion

ENTRYPOINT ["salt-minion", "-l", "debug"]
CMD ["tail -f /dev/null"]
